### ISSUE TITLE
App crash when hitting the done button

### ISSUE THREAD

**Issue by hoffiAT** [NielsMasdorp/Speculum-Android#25]
Hi, the app crashes when i hit the done button after the configuration, any idea?

**Comment by NielsMasdorp** [comment]
Hi, this could have a lot of reasons. What device/Android version are you running it on?

**Comment by hoffiAT** [comment]
i run 4.1. (SDK15) 
these errors occure:

03-26 19:04:53.173 10085-10085/com.nielsmasdorp.speculum W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40c2f2a0)
03-26 19:04:53.183 10085-10085/com.nielsmasdorp.speculum E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nielsmasdorp.speculum/com.nielsmasdorp.speculum.views.MainActivity}: android.view.InflateException: Binary XML file line #13: Error inflating class TextClock
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:137)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class TextClock
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:698)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                               at android.view.ViewStub.inflate(ViewStub.java:258)
                                                                               at com.nielsmasdorp.speculum.views.MainActivity.onCreate(MainActivity.java:154)
                                                                               at android.app.Activity.performCreate(Activity.java:5008)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
                                                                            Caused by: java.lang.ClassNotFoundException: android.view.TextClock
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:552)
                                                                               at android.view.LayoutInflater.onCreateView(LayoutInflater.java:643)
                                                                               at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
                                                                               at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:749) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                               at android.view.ViewStub.inflate(ViewStub.java:258) 
                                                                               at com.nielsmasdorp.speculum.views.MainActivity.onCreate(MainActivity.java:154) 
                                                                               at android.app.Activity.performCreate(Activity.java:5008) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by NielsMasdorp** [comment]
The min SDK for the app is 19. TextClock is not available for your SDK, so unfortunately the app won't work on your device.
